name: Check and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: latest

    - name: Configure Haxelib
      run: |
        haxelib setup /home/runner/haxe/haxelib/
        haxelib install formatter 1.16.0
        haxelib install checkstyle 2.9.0
        haxelib install format 3.6.0
        haxelib install utest 1.13.2
        haxelib git haxetoml https://github.com/codescapade/haxetoml.git

    - name: Linting
      run: haxe hxml/lint.hxml

    - name: Tests
      run: haxe hxml/test.hxml