name: Check and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: latest

    - name: Configure Haxelib
      run: |
        haxelib setup /home/runner/haxe/haxelib/
        haxelib install formatter
        haxelib install checkstyle
        haxelib dev jume-tools .

    - name: Formatting
      run: haxelib run formatter -s src -s tests --check

    - name: Linting
      run: haxelib run checkstyle -s src -s tests --exitcode

    - name: Tests
      run: haxe hxml/test.hxml